name: sum_region
description: sales and count
tableName: transform
updatedAt: "2025-04-15T11:52:48.916Z"
metricQuery:
  exploreName: transform
  dimensions:
    - transform_region
  metrics:
    - transform_sales_region_sum_sales
    - transform_count_region_sum_count
  filters: {}
  sorts:
    - fieldId: transform_region
      descending: false
  limit: 500
  metricOverrides: {}
  tableCalculations: []
  additionalMetrics:
    - name: sales_region_sum_sales
      label: region_sum_sales
      description: "Sum of Sales on the table Transform "
      uuid: 5a50b5a0-17fe-4ca8-b931-5ede780c400b
      sql: ${TABLE}.sales
      table: transform
      type: sum
      baseDimensionName: sales
      formatOptions:
        type: number
        separator: default
    - name: count_region_sum_count
      label: region_sum_count
      description: "Sum of Count on the table Transform "
      uuid: 54cdb496-f105-4894-98e9-f20f03ffe8d2
      sql: ${TABLE}.count
      table: transform
      type: sum
      baseDimensionName: count
      formatOptions:
        type: number
        separator: default
  customDimensions: []
chartConfig:
  type: table
  config:
    columns: {}
    metricsAsRows: false
    showSubtotals: false
    hideRowNumbers: false
    showTableNames: true
    showResultsTotal: false
    showRowCalculation: false
    showColumnCalculation: false
    conditionalFormattings:
      - rule:
          max: 99999999
          min: 0
        color:
          end: "#1563d1"
          start: "#ffffff"
          steps: 5
        target:
          fieldId: transform_sales_region_sum_sales
      - rule:
          max: 9999
          min: 0
        color:
          end: "#ee6666"
          start: "#ffffff"
          steps: 5
        target:
          fieldId: transform_count_region_sum_count
slug: sum-region
tableConfig:
  columnOrder:
    - transform_region
    - transform_sales_region_sum_sales
    - transform_count_region_sum_count
spaceSlug: shared
version: 1
downloadedAt: "2025-04-28T11:59:34.820Z"
